# Generated by Django 3.2.5 on 2022-08-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='njitem',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='njitem',
            name='poster_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
